### ISSUE TITLE
FeatureRequest # export label dataset 

### ISSUE THREAD

**Issue by a31amit** [TCK2001/Advanced_annotation_app#1]
Good effort to keep thing simple yet effective approach. Wondering if there is any plan to make dataset export from UI ?

**Comment by TCK2001** [comment]
Thank you for your interest in my side project !

Currently, It's unable to export to data.
However, if you need it ,
please let me know the format in which you would like to export the data (ex : x,y,x,y)
and i will add that functionality for you !

thanks

**Comment by a31amit** [comment]
As of now starting with yolo compatible should work
